### ISSUE TITLE
Convert `talks.json` into markdown files, like events

### ISSUE THREAD

**Issue by davidwesst** [davidwesst/davidwesst.github.io#226]
To remain consistent with other content on the site, `talks.json` should be converted into markdown files.

# TODO

- [ ] Create MD files for all talks with data in the front matter
- [ ] Remove page (`src/pages/talk.html`) and ensure all talks still work
- [ ] Delete `talks.json`

**Comment by davidwesst** [comment]
Completed with #218
